Debug.o: util/Debug.cc util/Debug.h util/Bitmask.h util/basics.h \
 mach/bitstrops.h mach/platform.h util/SpinLock.h mach/Processor.h \
 util/Log.h kern/globals.h mach/APIC.h mach/CPU.h mach/Memory.h
Log.o: util/Log.cc util/Log.h util/basics.h util/Bitmask.h \
 mach/bitstrops.h mach/platform.h kern/globals.h dev/IODev.h dev/Screen.h \
 extern/stl/screenbuf.h
Device.o: dev/Device.cc util/Log.h util/basics.h util/Bitmask.h \
 mach/bitstrops.h mach/platform.h kern/globals.h dev/Device.h \
 mach/Machine.h mach/Descriptors.h
Keyboard.o: dev/Keyboard.cc mach/APIC.h util/basics.h mach/platform.h \
 dev/Keyboard.h dev/Device.h mach/Machine.h mach/Descriptors.h kern/PCQ.h \
 util/Log.h util/Bitmask.h mach/bitstrops.h kern/globals.h \
 util/SpinLock.h mach/Processor.h mach/CPU.h mach/Memory.h kern/Kernel.h \
 kern/AddressSpace.h util/BuddyMap.h mach/PageManager.h util/Debug.h \
 kern/FrameManager.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h kern/Scheduler.h util/EmbeddedQueue.h util/Log.h \
 kern/Thread.h mach/stack.h
RTC.o: dev/RTC.cc mach/APIC.h util/basics.h mach/platform.h dev/RTC.h \
 dev/Device.h mach/Machine.h mach/Descriptors.h
ACPI.o: mach/ACPI.cc extern/acpica/source/include/acpi.h \
 extern/acpica/source/include/platform/acenv.h \
 extern/acpica/source/include/platform/ackos.h \
 extern/acpica/source/include/platform/acgcc.h \
 extern/acpica/source/include/acnames.h \
 extern/acpica/source/include/actypes.h \
 extern/acpica/source/include/acexcep.h \
 extern/acpica/source/include/actbl.h \
 extern/acpica/source/include/actbl1.h \
 extern/acpica/source/include/actbl2.h \
 extern/acpica/source/include/actbl3.h \
 extern/acpica/source/include/acoutput.h \
 extern/acpica/source/include/acrestyp.h \
 extern/acpica/source/include/acpiosxf.h \
 extern/acpica/source/include/acpixf.h \
 extern/acpica/source/include/acconfig.h util/BlindHeap.h util/basics.h \
 mach/platform.h util/Log.h util/Bitmask.h mach/bitstrops.h \
 kern/globals.h util/BlockingSync.h util/EmbeddedQueue.h util/Log.h \
 util/SpinLock.h mach/Processor.h mach/APIC.h mach/CPU.h mach/Memory.h \
 kern/Kernel.h kern/AddressSpace.h util/BuddyMap.h mach/PageManager.h \
 util/Debug.h kern/FrameManager.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h kern/Scheduler.h kern/Thread.h mach/stack.h \
 mach/Machine.h mach/Descriptors.h mach/PCI.h
APIC.o: mach/APIC.cc mach/APIC.h util/basics.h mach/platform.h
CPU.o: mach/CPU.cc mach/CPU.h util/basics.h mach/platform.h
Machine.o: mach/Machine.cc extern/multiboot/multiboot2.h mach/Machine.h \
 mach/Descriptors.h util/basics.h mach/platform.h mach/PageManager.h \
 util/Log.h util/Bitmask.h mach/bitstrops.h kern/globals.h util/Debug.h \
 util/SpinLock.h mach/Processor.h mach/APIC.h mach/CPU.h mach/Memory.h \
 kern/FrameManager.h util/BuddyMap.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h mach/PCI.h mach/asm_functions.h mach/isr_wrapper.h \
 dev/Keyboard.h dev/Device.h kern/PCQ.h kern/Kernel.h kern/AddressSpace.h \
 kern/Scheduler.h util/EmbeddedQueue.h util/Log.h kern/Thread.h \
 mach/stack.h dev/RTC.h dev/Screen.h
PCI.o: mach/PCI.cc mach/PCI.h util/basics.h util/Log.h util/Bitmask.h \
 mach/bitstrops.h mach/platform.h kern/globals.h
PageManager.o: mach/PageManager.cc mach/PageManager.h util/Log.h \
 util/basics.h util/Bitmask.h mach/bitstrops.h mach/platform.h \
 kern/globals.h util/Debug.h util/SpinLock.h mach/Processor.h mach/APIC.h \
 mach/CPU.h mach/Memory.h kern/FrameManager.h util/BuddyMap.h \
 kern/KernelHeap.h extern/stl/mod_set extern/stl/mod_stl_tree.h \
 extern/stl/mod_stl_set.h util/CacheHeap.h util/BlockHeap.h
platform.o: mach/platform.cc mach/platform.h mach/asm_functions.h \
 util/basics.h
KernelHeap.o: kern/KernelHeap.cc util/Log.h util/basics.h util/Bitmask.h \
 mach/bitstrops.h mach/platform.h kern/globals.h kern/Kernel.h \
 kern/AddressSpace.h util/BuddyMap.h util/SpinLock.h mach/Processor.h \
 mach/APIC.h mach/CPU.h mach/Memory.h mach/PageManager.h util/Debug.h \
 kern/FrameManager.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h kern/Scheduler.h util/EmbeddedQueue.h util/Log.h
Scheduler.o: kern/Scheduler.cc util/Log.h util/basics.h util/Bitmask.h \
 mach/bitstrops.h mach/platform.h kern/globals.h mach/Processor.h \
 mach/APIC.h mach/CPU.h mach/Memory.h mach/stack.h kern/Scheduler.h \
 util/EmbeddedQueue.h util/Log.h util/SpinLock.h kern/Thread.h \
 kern/Kernel.h kern/AddressSpace.h util/BuddyMap.h mach/PageManager.h \
 util/Debug.h kern/FrameManager.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h
Thread.o: kern/Thread.cc mach/CPU.h util/basics.h mach/platform.h \
 kern/Thread.h util/EmbeddedQueue.h util/Log.h util/Bitmask.h \
 mach/bitstrops.h kern/globals.h mach/stack.h kern/Kernel.h \
 kern/AddressSpace.h util/BuddyMap.h util/SpinLock.h mach/Processor.h \
 util/Log.h mach/APIC.h mach/Memory.h mach/PageManager.h util/Debug.h \
 kern/FrameManager.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h kern/Scheduler.h
kernel.o: kern/kernel.cc util/Log.h util/basics.h util/Bitmask.h \
 mach/bitstrops.h mach/platform.h kern/globals.h mach/Machine.h \
 mach/Descriptors.h mach/Processor.h mach/APIC.h mach/CPU.h mach/Memory.h \
 kern/AddressSpace.h util/BuddyMap.h util/SpinLock.h mach/PageManager.h \
 util/Debug.h kern/FrameManager.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h kern/Scheduler.h util/EmbeddedQueue.h util/Log.h \
 kern/Thread.h mach/stack.h kern/Kernel.h
Debug.s: util/Debug.cc util/Debug.h util/Bitmask.h util/basics.h \
 mach/bitstrops.h mach/platform.h util/SpinLock.h mach/Processor.h \
 util/Log.h kern/globals.h mach/APIC.h mach/CPU.h mach/Memory.h
Log.s: util/Log.cc util/Log.h util/basics.h util/Bitmask.h \
 mach/bitstrops.h mach/platform.h kern/globals.h dev/IODev.h dev/Screen.h \
 extern/stl/screenbuf.h
Device.s: dev/Device.cc util/Log.h util/basics.h util/Bitmask.h \
 mach/bitstrops.h mach/platform.h kern/globals.h dev/Device.h \
 mach/Machine.h mach/Descriptors.h
Keyboard.s: dev/Keyboard.cc mach/APIC.h util/basics.h mach/platform.h \
 dev/Keyboard.h dev/Device.h mach/Machine.h mach/Descriptors.h kern/PCQ.h \
 util/Log.h util/Bitmask.h mach/bitstrops.h kern/globals.h \
 util/SpinLock.h mach/Processor.h mach/CPU.h mach/Memory.h kern/Kernel.h \
 kern/AddressSpace.h util/BuddyMap.h mach/PageManager.h util/Debug.h \
 kern/FrameManager.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h kern/Scheduler.h util/EmbeddedQueue.h util/Log.h \
 kern/Thread.h mach/stack.h
RTC.s: dev/RTC.cc mach/APIC.h util/basics.h mach/platform.h dev/RTC.h \
 dev/Device.h mach/Machine.h mach/Descriptors.h
ACPI.s: mach/ACPI.cc extern/acpica/source/include/acpi.h \
 extern/acpica/source/include/platform/acenv.h \
 extern/acpica/source/include/platform/ackos.h \
 extern/acpica/source/include/platform/acgcc.h \
 extern/acpica/source/include/acnames.h \
 extern/acpica/source/include/actypes.h \
 extern/acpica/source/include/acexcep.h \
 extern/acpica/source/include/actbl.h \
 extern/acpica/source/include/actbl1.h \
 extern/acpica/source/include/actbl2.h \
 extern/acpica/source/include/actbl3.h \
 extern/acpica/source/include/acoutput.h \
 extern/acpica/source/include/acrestyp.h \
 extern/acpica/source/include/acpiosxf.h \
 extern/acpica/source/include/acpixf.h \
 extern/acpica/source/include/acconfig.h util/BlindHeap.h util/basics.h \
 mach/platform.h util/Log.h util/Bitmask.h mach/bitstrops.h \
 kern/globals.h util/BlockingSync.h util/EmbeddedQueue.h util/Log.h \
 util/SpinLock.h mach/Processor.h mach/APIC.h mach/CPU.h mach/Memory.h \
 kern/Kernel.h kern/AddressSpace.h util/BuddyMap.h mach/PageManager.h \
 util/Debug.h kern/FrameManager.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h kern/Scheduler.h kern/Thread.h mach/stack.h \
 mach/Machine.h mach/Descriptors.h mach/PCI.h
APIC.s: mach/APIC.cc mach/APIC.h util/basics.h mach/platform.h
CPU.s: mach/CPU.cc mach/CPU.h util/basics.h mach/platform.h
Machine.s: mach/Machine.cc extern/multiboot/multiboot2.h mach/Machine.h \
 mach/Descriptors.h util/basics.h mach/platform.h mach/PageManager.h \
 util/Log.h util/Bitmask.h mach/bitstrops.h kern/globals.h util/Debug.h \
 util/SpinLock.h mach/Processor.h mach/APIC.h mach/CPU.h mach/Memory.h \
 kern/FrameManager.h util/BuddyMap.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h mach/PCI.h mach/asm_functions.h mach/isr_wrapper.h \
 dev/Keyboard.h dev/Device.h kern/PCQ.h kern/Kernel.h kern/AddressSpace.h \
 kern/Scheduler.h util/EmbeddedQueue.h util/Log.h kern/Thread.h \
 mach/stack.h dev/RTC.h dev/Screen.h
PCI.s: mach/PCI.cc mach/PCI.h util/basics.h util/Log.h util/Bitmask.h \
 mach/bitstrops.h mach/platform.h kern/globals.h
PageManager.s: mach/PageManager.cc mach/PageManager.h util/Log.h \
 util/basics.h util/Bitmask.h mach/bitstrops.h mach/platform.h \
 kern/globals.h util/Debug.h util/SpinLock.h mach/Processor.h mach/APIC.h \
 mach/CPU.h mach/Memory.h kern/FrameManager.h util/BuddyMap.h \
 kern/KernelHeap.h extern/stl/mod_set extern/stl/mod_stl_tree.h \
 extern/stl/mod_stl_set.h util/CacheHeap.h util/BlockHeap.h
platform.s: mach/platform.cc mach/platform.h mach/asm_functions.h \
 util/basics.h
KernelHeap.s: kern/KernelHeap.cc util/Log.h util/basics.h util/Bitmask.h \
 mach/bitstrops.h mach/platform.h kern/globals.h kern/Kernel.h \
 kern/AddressSpace.h util/BuddyMap.h util/SpinLock.h mach/Processor.h \
 mach/APIC.h mach/CPU.h mach/Memory.h mach/PageManager.h util/Debug.h \
 kern/FrameManager.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h kern/Scheduler.h util/EmbeddedQueue.h util/Log.h
Scheduler.s: kern/Scheduler.cc util/Log.h util/basics.h util/Bitmask.h \
 mach/bitstrops.h mach/platform.h kern/globals.h mach/Processor.h \
 mach/APIC.h mach/CPU.h mach/Memory.h mach/stack.h kern/Scheduler.h \
 util/EmbeddedQueue.h util/Log.h util/SpinLock.h kern/Thread.h \
 kern/Kernel.h kern/AddressSpace.h util/BuddyMap.h mach/PageManager.h \
 util/Debug.h kern/FrameManager.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h
Thread.s: kern/Thread.cc mach/CPU.h util/basics.h mach/platform.h \
 kern/Thread.h util/EmbeddedQueue.h util/Log.h util/Bitmask.h \
 mach/bitstrops.h kern/globals.h mach/stack.h kern/Kernel.h \
 kern/AddressSpace.h util/BuddyMap.h util/SpinLock.h mach/Processor.h \
 util/Log.h mach/APIC.h mach/Memory.h mach/PageManager.h util/Debug.h \
 kern/FrameManager.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h kern/Scheduler.h
kernel.s: kern/kernel.cc util/Log.h util/basics.h util/Bitmask.h \
 mach/bitstrops.h mach/platform.h kern/globals.h mach/Machine.h \
 mach/Descriptors.h mach/Processor.h mach/APIC.h mach/CPU.h mach/Memory.h \
 kern/AddressSpace.h util/BuddyMap.h util/SpinLock.h mach/PageManager.h \
 util/Debug.h kern/FrameManager.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h kern/Scheduler.h util/EmbeddedQueue.h util/Log.h \
 kern/Thread.h mach/stack.h kern/Kernel.h
Debug.e: util/Debug.cc util/Debug.h util/Bitmask.h util/basics.h \
 mach/bitstrops.h mach/platform.h util/SpinLock.h mach/Processor.h \
 util/Log.h kern/globals.h mach/APIC.h mach/CPU.h mach/Memory.h
Log.e: util/Log.cc util/Log.h util/basics.h util/Bitmask.h \
 mach/bitstrops.h mach/platform.h kern/globals.h dev/IODev.h dev/Screen.h \
 extern/stl/screenbuf.h
Device.e: dev/Device.cc util/Log.h util/basics.h util/Bitmask.h \
 mach/bitstrops.h mach/platform.h kern/globals.h dev/Device.h \
 mach/Machine.h mach/Descriptors.h
Keyboard.e: dev/Keyboard.cc mach/APIC.h util/basics.h mach/platform.h \
 dev/Keyboard.h dev/Device.h mach/Machine.h mach/Descriptors.h kern/PCQ.h \
 util/Log.h util/Bitmask.h mach/bitstrops.h kern/globals.h \
 util/SpinLock.h mach/Processor.h mach/CPU.h mach/Memory.h kern/Kernel.h \
 kern/AddressSpace.h util/BuddyMap.h mach/PageManager.h util/Debug.h \
 kern/FrameManager.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h kern/Scheduler.h util/EmbeddedQueue.h util/Log.h \
 kern/Thread.h mach/stack.h
RTC.e: dev/RTC.cc mach/APIC.h util/basics.h mach/platform.h dev/RTC.h \
 dev/Device.h mach/Machine.h mach/Descriptors.h
ACPI.e: mach/ACPI.cc extern/acpica/source/include/acpi.h \
 extern/acpica/source/include/platform/acenv.h \
 extern/acpica/source/include/platform/ackos.h \
 extern/acpica/source/include/platform/acgcc.h \
 extern/acpica/source/include/acnames.h \
 extern/acpica/source/include/actypes.h \
 extern/acpica/source/include/acexcep.h \
 extern/acpica/source/include/actbl.h \
 extern/acpica/source/include/actbl1.h \
 extern/acpica/source/include/actbl2.h \
 extern/acpica/source/include/actbl3.h \
 extern/acpica/source/include/acoutput.h \
 extern/acpica/source/include/acrestyp.h \
 extern/acpica/source/include/acpiosxf.h \
 extern/acpica/source/include/acpixf.h \
 extern/acpica/source/include/acconfig.h util/BlindHeap.h util/basics.h \
 mach/platform.h util/Log.h util/Bitmask.h mach/bitstrops.h \
 kern/globals.h util/BlockingSync.h util/EmbeddedQueue.h util/Log.h \
 util/SpinLock.h mach/Processor.h mach/APIC.h mach/CPU.h mach/Memory.h \
 kern/Kernel.h kern/AddressSpace.h util/BuddyMap.h mach/PageManager.h \
 util/Debug.h kern/FrameManager.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h kern/Scheduler.h kern/Thread.h mach/stack.h \
 mach/Machine.h mach/Descriptors.h mach/PCI.h
APIC.e: mach/APIC.cc mach/APIC.h util/basics.h mach/platform.h
CPU.e: mach/CPU.cc mach/CPU.h util/basics.h mach/platform.h
Machine.e: mach/Machine.cc extern/multiboot/multiboot2.h mach/Machine.h \
 mach/Descriptors.h util/basics.h mach/platform.h mach/PageManager.h \
 util/Log.h util/Bitmask.h mach/bitstrops.h kern/globals.h util/Debug.h \
 util/SpinLock.h mach/Processor.h mach/APIC.h mach/CPU.h mach/Memory.h \
 kern/FrameManager.h util/BuddyMap.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h mach/PCI.h mach/asm_functions.h mach/isr_wrapper.h \
 dev/Keyboard.h dev/Device.h kern/PCQ.h kern/Kernel.h kern/AddressSpace.h \
 kern/Scheduler.h util/EmbeddedQueue.h util/Log.h kern/Thread.h \
 mach/stack.h dev/RTC.h dev/Screen.h
PCI.e: mach/PCI.cc mach/PCI.h util/basics.h util/Log.h util/Bitmask.h \
 mach/bitstrops.h mach/platform.h kern/globals.h
PageManager.e: mach/PageManager.cc mach/PageManager.h util/Log.h \
 util/basics.h util/Bitmask.h mach/bitstrops.h mach/platform.h \
 kern/globals.h util/Debug.h util/SpinLock.h mach/Processor.h mach/APIC.h \
 mach/CPU.h mach/Memory.h kern/FrameManager.h util/BuddyMap.h \
 kern/KernelHeap.h extern/stl/mod_set extern/stl/mod_stl_tree.h \
 extern/stl/mod_stl_set.h util/CacheHeap.h util/BlockHeap.h
platform.e: mach/platform.cc mach/platform.h mach/asm_functions.h \
 util/basics.h
KernelHeap.e: kern/KernelHeap.cc util/Log.h util/basics.h util/Bitmask.h \
 mach/bitstrops.h mach/platform.h kern/globals.h kern/Kernel.h \
 kern/AddressSpace.h util/BuddyMap.h util/SpinLock.h mach/Processor.h \
 mach/APIC.h mach/CPU.h mach/Memory.h mach/PageManager.h util/Debug.h \
 kern/FrameManager.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h kern/Scheduler.h util/EmbeddedQueue.h util/Log.h
Scheduler.e: kern/Scheduler.cc util/Log.h util/basics.h util/Bitmask.h \
 mach/bitstrops.h mach/platform.h kern/globals.h mach/Processor.h \
 mach/APIC.h mach/CPU.h mach/Memory.h mach/stack.h kern/Scheduler.h \
 util/EmbeddedQueue.h util/Log.h util/SpinLock.h kern/Thread.h \
 kern/Kernel.h kern/AddressSpace.h util/BuddyMap.h mach/PageManager.h \
 util/Debug.h kern/FrameManager.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h
Thread.e: kern/Thread.cc mach/CPU.h util/basics.h mach/platform.h \
 kern/Thread.h util/EmbeddedQueue.h util/Log.h util/Bitmask.h \
 mach/bitstrops.h kern/globals.h mach/stack.h kern/Kernel.h \
 kern/AddressSpace.h util/BuddyMap.h util/SpinLock.h mach/Processor.h \
 util/Log.h mach/APIC.h mach/Memory.h mach/PageManager.h util/Debug.h \
 kern/FrameManager.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h kern/Scheduler.h
kernel.e: kern/kernel.cc util/Log.h util/basics.h util/Bitmask.h \
 mach/bitstrops.h mach/platform.h kern/globals.h mach/Machine.h \
 mach/Descriptors.h mach/Processor.h mach/APIC.h mach/CPU.h mach/Memory.h \
 kern/AddressSpace.h util/BuddyMap.h util/SpinLock.h mach/PageManager.h \
 util/Debug.h kern/FrameManager.h kern/KernelHeap.h extern/stl/mod_set \
 extern/stl/mod_stl_tree.h extern/stl/mod_stl_set.h util/CacheHeap.h \
 util/BlockHeap.h kern/Scheduler.h util/EmbeddedQueue.h util/Log.h \
 kern/Thread.h mach/stack.h kern/Kernel.h
