PREFIX=/usr/local/cross
GCCVER=4.7.2
EXEPREFIX=$(PREFIX)/bin/x86_64-pc-kos
CXX=$(EXEPREFIX)-g++
CC=$(EXEPREFIX)-gcc
AS=$(EXEPREFIX)-as
AR=$(EXEPREFIX)-ar
LD=$(EXEPREFIX)-ld
OBJCOPY=$(EXEPREFIX)-objcopy
RANLIB=$(EXEPREFIX)-ranlib
STRIP=$(EXEPREFIX)-strip
GDB=$(EXEPREFIX)-gdb
NASM=nasm

VDISK=/tmp/kos.img
ISO=/tmp/kos.iso
USBDEV=/dev/sdb
IMAGE=$(ISO)
QEMU_BASE=qemu-system-x86_64\
	-debugcon file:/tmp/KOS.dbg -serial file:/tmp/KOS.serial\
	-m 1024 -smp cores=2,threads=1,sockets=1
#QEMU_BASE+=-d int,cpu_reset
QEMU_HD=$(QEMU_BASE) -hda $(VDISK)
QEMU_ISO=$(QEMU_BASE) -cdrom $(ISO)
QEMU=$(QEMU_ISO)

KERNBASE=0xFFFFFFFF80000000
BOOTMEM=0x600000
BOOT16=0x1000

CFGFLAGS=-I. -DKERNBASE=$(KERNBASE) -DBOOTMEM=$(BOOTMEM) -DBOOT16=$(BOOT16)\
	-D__KOS__

DBGFLAGS=-g

#OPTFLAGS=-O2

LANGFLAGS=-std=c++11 -fno-exceptions -fno-rtti

COMPFLAGS=-fno-common -Wall -Wextra -Wno-unused-function -Wno-unused-parameter

MACHFLAGS=-ffreestanding -m64 -mcmodel=kernel -mno-red-zone\
	-mno-mmx -mno-sse -mno-sse2 -mno-sse3 -mno-3dnow

TSTFLAGS=$(CFGFLAGS) $(OPTFLAGS) $(DBGFLAGS) $(LANGFLAGS) $(COMPFLAGS)
PREFLAGS=$(CFGFLAGS) $(OPTFLAGS)             $(LANGFLAGS) $(COMPFLAGS) $(MACHFLAGS)
CXXFLAGS=$(CFGFLAGS) $(OPTFLAGS) $(DBGFLAGS) $(LANGFLAGS) $(COMPFLAGS) $(MACHFLAGS)
CFLAGS=              $(OPTFLAGS) $(DBGFLAGS)              $(COMPFLAGS) $(MACHFLAGS)

ASFLAGS=-g

NASMFLAGS=-felf64 -g -DKERNBASE=$(KERNBASE) -DBOOTMEM=$(BOOTMEM) -DBOOT16=$(BOOT16)

LDFLAGS=--defsym=KERNBASE=$(KERNBASE) --defsym=BOOTMEM=$(BOOTMEM) -static\
	-L$(PREFIX)/x86_64-pc-kos/lib -lstdc++ -lc\
	-L$(PREFIX)/lib/gcc/x86_64-pc-kos/$(GCCVER) -lgcc
#LDFLAGS+=-nostartfiles # only with gcc/g++ as linker
